### PR TITLE
Add accessToken field to firebase.auth.AuthCrendential typings

### PR DESCRIPTION
**Pull request by GCrispino**
Add accessToken field to firebase.auth.AuthCrendential typings defined at /packages/firebase/index.d.ts

### CODE REVIEW

**Comment by GCrispino** [comment]
I signed it!

**Comment by bojeil-google** [comment]
This is not correct. You need to cast the `AuthCredential` to an `OAuthCredential` which I assume you are getting after OAuth sign-in. The `accessToken` is defined on the latter: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth-types/index.d.ts#L249

An `AuthCredential` can be a phone, email/password, etc and nothing to do with OAuth.

**Comment by GCrispino** [comment]
Got it then! It just was not clear to me as following the firebase auth's getting started. Maybe adding a TypeScript example would be a nice idea?

**Comment by GCrispino** [comment]
Got it then! It just was not clear to me as following the firebase auth's getting started. 
However, I can't find the `OAuthCredential` type when using the imported firebase's module. The only type that is visible to me is `OAuthProvider`, through the distributed index.d.ts file.

**Comment by Feiyang1** [comment]
@bojeil-google Do we want to expose OAuthCredential to the public?

**Comment by bojeil-google** [comment]
Hey @Feiyang1, `OAuthCredential` should already be public: https://firebase.google.com/docs/reference/js/firebase.auth.OAuthCredential

**Comment by Feiyang1** [comment]
I made a PR https://github.com/firebase/firebase-js-sdk/pull/1559
Please take a look

**Comment by tevanuwat** [comment]
Will my iphone be protected by this Firebase?

**Comment by Feiyang1** [comment]
Closing it since https://github.com/firebase/firebase-js-sdk/pull/1559 addressed the issue.

**Pull request closed without merging**
