### PR TITLE
Specify types of observer and next function for UploadTask.on

### PR DESCRIPTION
**Pull request by sphippen**
Fix for Storage types described in #620.

### CODE REVIEW

**Comment by sphippen** [comment]
@henriiik I rewrote your commit into this repo but it looks like you haven't agreed to a Google CLA. If you're fine signing it then go ahead and do it, and Googlebot should become happy with this commit. If not I'll write a fix myself.

**Comment by henriiik** [comment]
I have signed it now. Thanks for creating the PR! :)

**Comment by sphippen** [comment]
Adding a comment to get Googlebot to run again.

**Comment by henriiik** [comment]
I am okay with my commit being contributed to this project. :)

**Comment by sphippen** [comment]
Okay, great. Thanks again!

**Pull request merged**
