### PR TITLE
Update rtdb types

### LINKED ISSUE #306: Updates to Database Type Definitions
* Expose `ThenableReference` type from the database type definitions.
* Currently `then()` and `catch()` methods are exposed from the `Reference` type, which doesn't seem to be correct. Those belong in `ThenableReference`.
* Add `EventType` type:

```
type EventType = 'value' | 'child_added' | 'child_changed' | 'child_moved' | 'child_removed';
```

### PR DESCRIPTION
**Pull request by Crazometer**
Updated some of the type definitions.

Fixes #306, #555.

### CODE REVIEW

**Comment by schmidt-sebastian** [comment]
Thanks for sending this over. Due to how our repo is structured, these changes need to be replicated in one more place (https://github.com/firebase/firebase-js-sdk/blob/dd11cd17aada45a19732d6517a7d740e722546d2/packages/firebase/index.d.ts). I will do this myself once CI passes and this PR is merged.

**Comment by Crazometer** [comment]
Thanks!

**Comment by jamesdaniels** [comment]
FYI while being more explicit is useful, mind that changes such as this are breaking changes for typescript users. https://travis-ci.org/angular/angularfire2/jobs/386001074

**Comment by jamesdaniels** [comment]
@schmidt-sebastian please watch out for what should be major changes to the types in future PRs. Angularfire is still in RC still so I'm not stressing out too much but this could break the build for anyone else using TS. 

IMO correct thing to do would be:

```ts
// TODO(semver): drop "string" in 6.0 release
type EventType = string | 'value' | 'child_added' | 'child_changed' | 'child_moved' | 'child_removed';
```

**Pull request merged**
