### PR TITLE
VertexAI: update testing to clone mock responses from shared repo

### PR DESCRIPTION
**Pull request by tanzimfh**
This removes mock responses from this repo and updates the test setup process to clone them from the new [shared repo](https://github.com/firebaseextended/vertexai-sdk-test-data/).

### CODE REVIEW

**Review by dlarocque — APPROVED** [review]
Nice!

We talked about this earlier, but I just want to confirm: When a change to the expected responses are made, those changes will stay in a separate branch until the changes in the backend go live?

So, the process would be:
1. Breaking changes to the response format are proposed/staged, and the new responses are checked into a branch (e.g. `staging`) in the golden files repo.
2. When we get around to fixing how we handle the new responses, we would add `git checkout staging` to the `testsetup` step to test against the new version of the responses.
3. When the changes to the responses go live, `staging` is merged into `master`, and we make another PR, removing `git checkout staging` from `testsetup`.

**Comment by tanzimfh** [comment]
@dlarocque That's just an idea I had, it's not documented anywhere.

That process is a bit cumbersome, but I don't think it should be an issue if breaking changes don't come too often. Keep in mind that non-breaking changes can be merged directly to `main`, and the golden files repo's CI will run the SDKs' unit tests for Vertex to prevent accidental breakages (see [this PR](https://github.com/FirebaseExtended/vertexai-sdk-test-data/pull/2) that runs the iOS tests).

@hsubox76 @andrewheard @rlazo @davidmotson Please share any thoughts. I can document this in the golden files repo when everyone agrees on a solution 🤠

**Comment by rlazo** [comment]
> Nice!
> 
> We talked about this earlier, but I just want to confirm: When a change to the expected responses are made, those changes will stay in a separate branch until the changes in the backend go live?
> 
> So, the process would be:
> 
> 1. Breaking changes to the response format are proposed/staged, and the new responses are checked into a branch (e.g. `staging`) in the golden files repo.
> 2. When we get around to fixing how we handle the new responses, we would add `git checkout staging` to the `testsetup` step to test against the new version of the responses.
> 3. When the changes to the responses go live, `staging` is merged into `master`, and we make another PR, removing `git checkout staging` from `testsetup`.
> 
> If this is the case, or there is another process, is that documented somewhere?

Hey Daniel, would this process work for you?

1. Breaking changes to the response are checked into the `main` branch of the golden files repo.
2. This will, potentially, break your code. Then you'll keep having failures until the code is fixed.
  2.1 If you need the code to pass tests **now**, because you are working on something else, you can change your code to checkout the commit before the breaking change. 
  2.2 Once your code is fixed, you can start checking out `main` HEAD again


The main advantage of this over the previous one is that moving things around are done in only one repo (platform) rather than 2 (platform & golden files). This makes maintainance of the golden files easier as adding new tests is a single step process.

WDYT?

**Comment by dlarocque** [comment]
> That process is a bit cumbersome, but I don't think it should be an issue if breaking changes don't come too often. 

Agreed!

> Keep in mind that non-breaking changes can be merged directly to `main`, and the golden files repo's CI will run the SDKs' unit tests for Vertex to prevent accidental breakages (see [this PR](https://github.com/FirebaseExtended/vertexai-sdk-test-data/pull/2) that runs the iOS tests).

Oh I didn't see this- nice!

**Comment by dlarocque** [comment]
> Hey Daniel, would this process work for you?
> 
> 1. Breaking changes to the response are checked into the `main` branch of the golden files repo.
> 2. This will, potentially, break your code. Then you'll keep having failures until the code is fixed.
>    2.1 If you need the code to pass tests **now**, because you are working on something else, you can change your code to checkout the commit before the breaking change.
>    2.2 Once your code is fixed, you can start checking out `main` HEAD again

That sounds good to me! Would the breaking changes only be checked into main once they go live in the backend?

**Comment by rlazo** [comment]
Ideally they would go live asap, because we can then use the tests to
develop the code earlier

**Comment by andrewheard** [comment]
> 1. Breaking changes to the response are checked into the `main` branch of the golden files repo.
> 2. This will, potentially, break your code. Then you'll keep having failures until the code is fixed.
>    2.1 If you need the code to pass tests **now**, because you are working on something else, you can change your code to checkout the commit before the breaking change.
>    2.2 Once your code is fixed, you can start checking out `main` HEAD again

This sounds reasonable to me as well on the Swift side. I think we'll just need to make sure it's well documented in the workflows / scripts so the rest of our team members can easily spot the issue and temporarily work around it (or know to ignore CI failures).

If breakages become too frequent, one other possible process I can think of: 
1. The scripts in each repo could checkout a specific commit (or semver tag) from [`vertexai-sdk-test-data`](https://github.com/firebaseextended/vertexai-sdk-test-data/).
2. CI workflows in each repo could add a warning comment in PRs if not using the latest commit / tag from `vertexai-sdk-test-data` (to suggest that you update).

cc: @paulb777 in case you have ideas or opinions on processes.

**Comment by dlarocque** [comment]
I do feel a bit uneasy about CI being guaranteed to go red any time there is a breaking change to the test responses, particularly on branches/PRs that don't make changes related to vertex, where the owner of the branch isn't aware of any of this.

**Comment by rlazo** [comment]
> I do feel a bit uneasy about CI being guaranteed to go red any time there is a breaking change to the test responses, particularly on branches/PRs that don't make changes related to vertex, where the owner of the branch isn't aware of any of this.
> 
> I suppose we could work on a fix _before_ the breaking changes are merged to main by modifying our test scripts to checkout the commit with the breaking changes, but then if a branch isn't rebased on top of the fix its CI will still go red anyway.

Do JS run all the tests for all the products for each PR?

**Comment by rlazo** [comment]
> > 1. Breaking changes to the response are checked into the `main` branch of the golden files repo.
> > 2. This will, potentially, break your code. Then you'll keep having failures until the code is fixed.
> >    2.1 If you need the code to pass tests **now**, because you are working on something else, you can change your code to checkout the commit before the breaking change.
> >    2.2 Once your code is fixed, you can start checking out `main` HEAD again
> 
> This sounds reasonable to me as well on the Swift side. I think we'll just need to make sure it's well documented in the workflows / scripts so the rest of our team members can easily spot the issue and temporarily work around it (or know to ignore CI failures).
> 
> If breakages become too frequent, one other possible process I can think of:
> 
> 1. The scripts in each repo could checkout a specific commit (or semver tag) from [`vertexai-sdk-test-data`](https://github.com/firebaseextended/vertexai-sdk-test-data/).
> 2. CI workflows in each repo could add a warning comment in PRs if not using the latest commit / tag from `vertexai-sdk-test-data` (to suggest that you update).
> 
> cc: @paulb777 in case you have ideas or opinions on processes.

Yes, we need to document this so it's clear what to do when these errors are found. 

And as you said, these particular breaking changes should be rare, as they not only break SDKs, but anybody using the REST API directly.

**Comment by dlarocque** [comment]
> > I do feel a bit uneasy about CI being guaranteed to go red any time there is a breaking change to the test responses, particularly on branches/PRs that don't make changes related to vertex, where the owner of the branch isn't aware of any of this.
> > I suppose we could work on a fix _before_ the breaking changes are merged to main by modifying our test scripts to checkout the commit with the breaking changes, but then if a branch isn't rebased on top of the fix its CI will still go red anyway.
> 
> Do JS run all the tests for all the products for each PR?

Yeah, we have a workflow that runs all the tests. 

From this PR: https://github.com/firebase/firebase-js-sdk/actions/runs/9688342328/job/26735897472?pr=8333#step:8:1

**Comment by rlazo** [comment]
Here's a proposal:

The golden test repository will tag all commits in a semver-ish manner

- Major versions for any changes to an existing file
- Minor versions for adding new files

This way you know that the contents in the commit tagged v2.2 and v2.6 are compatible and will not break your tests.

Furthermore, you can "pin" your repo to a major version, but get updates for the minor versions. For example major version `5`, by running

`git tag -l 'v5.*' | tail -n1`

this will return the latest tag in the `v5` group. To bump to the next major version you would have to manually edit that command to use `v6.*` instead.

This will help keep the maintenance of the golden file repo low, while enabling platform teams to use a known "good" version.

**Review by hsubox76 — APPROVED** [review]

**Pull request merged**
