### PR TITLE
Add `await` to `onBackgroundMessage` callback

### PR DESCRIPTION
**Pull request by zwu52**
To resolve [issue](https://github.com/firebase/firebase-js-sdk/issues/5516)

### CODE REVIEW

**Review by philippevezina — APPROVED** [review]
Looks good to me 👍🏼 I've been having this issue and looking for an alternative until this fix is released. It looks like using [`synchronized-promise`](https://www.npmjs.com/package/synchronized-promise) in a compiled Webpack app works.

```js
import { initializeApp } from 'firebase/app'
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw'
import sp from 'synchronized-promise'

const showNotification = sp((title, options) => {
  return self.registration.showNotification(title, options);
});

onBackgroundMessage(messaging, () => {
  showNotification('Title', {}));
});
```

**Comment by Eros1990** [comment]
> Looks good to me 👍🏼 I've been having this issue and looking for an alternative until this fix is released. It looks like using [`synchronized-promise`](https://www.npmjs.com/package/synchronized-promise) in a compiled Webpack app works.
> 
> ```js
> import { initializeApp } from 'firebase/app'
> import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw'
> import sp from 'synchronized-promise'
> 
> const showNotification = sp((title, options) => {
>   return self.registration.showNotification(title, options);
> });
> 
> onBackgroundMessage(messaging, () => {
>   showNotification('Title', {}));
> });
> ```
This solution doesn't work in a browser

**Comment by philippevezina** [comment]
> > Looks good to me 👍🏼 I've been having this issue and looking for an alternative until this fix is released. It looks like using [`synchronized-promise`](https://www.npmjs.com/package/synchronized-promise) in a compiled Webpack app works.
> > ```js
> > import { initializeApp } from 'firebase/app'
> > import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw'
> > import sp from 'synchronized-promise'
> > 
> > const showNotification = sp((title, options) => {
> >   return self.registration.showNotification(title, options);
> > });
> > 
> > onBackgroundMessage(messaging, () => {
> >   showNotification('Title', {}));
> > });
> > ```
> 
> This solution doesn't work in a browser

You are right, this is actually raising an error that I hadn't noticed when developing. That said, my notification is still displaying properly without Chrome's default notification, and it seems like the thrown error might be what is "fixing" the initial problem 😅

**Comment by masterT** [comment]
@philippevezina It might work because your bundler added polyfill for `path` (required by `deasync` which is used in `synchronized-promise`).

**Review by hsubox76 — COMMENTED** [review]
Can you add a changeset?

**Review by hsubox76 — APPROVED** [review]

**Comment by masterT** [comment]
🙏

**Comment by xblitz** [comment]
I am still having the same issues as described in #5516 ( currently on firebase@9.6.9 ) , getting 2 notifications windows, first is the `This site has been updated in the background`  and then my configured notification.
This is how I declared the onBackgroundMessage:
```javascript
onBackgroundMessage(messaging, (payload) => {
  const notificationTitle = "Message from " + payload.data["contact"];
  const notificationOptions = {
    body: payload.data["message"],
    icon: "/img/icons/android-chrome-192x192.png",
    data: payload.data,
  };
  self.registration.showNotification(notificationTitle, notificationOptions);
  console.log("[service-worker] Received background message ", payload);
});
```

**Comment by Eros1990** [comment]
> I am still having the same issues as described in #5516 ( currently on firebase@9.6.9 ) , getting 2 notifications windows, first is the `This site has been updated in the background` and then my configured notification. This is how I declared the onBackgroundMessage:
> 
> ```js
> onBackgroundMessage(messaging, (payload) => {
>   const notificationTitle = "Message from " + payload.data["contact"];
>   const notificationOptions = {
>     body: payload.data["message"],
>     icon: "/img/icons/android-chrome-192x192.png",
>     data: payload.data,
>   };
>   self.registration.showNotification(notificationTitle, notification options);
>   console.log("[service-worker] Received background message ", payload);
> });
> ```

Did you try something like this?

```js
onBackgroundMessage(messaging, (payload) => {
  const notificationTitle = "Message from " + payload.data["contact"];
  const notificationOptions = {
    body: payload.data["message"],
    icon: "/img/icons/android-chrome-192x192.png",
    data: payload.data,
  };
  console.log("[service-worker] Received background message ", payload);
  return self.registration.showNotification(notificationTitle, notificationOptions);
});
```

**Comment by xblitz** [comment]
oh yeah, for some reason I didn't see that last comment on the original issue. so I just did, and that actually works. but I really don't understand why! I mean, if it works it's all good, but I am curious though as to why this works.

**Comment by philippevezina** [comment]
> oh yeah, for some reason I didn't see that last comment on the original issue (or didn't see that it was adding a `return`). so now I just did, and that actually works. but I really don't understand why! I mean, if it works it's all good, but I am curious though as to why this works.

[`self.registration.showNotification`](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification#return_value) is actually `async`. Firebase uses `await` on the callback method you pass to `onBackgroundMessage` which makes it wait for the notification to be completely sent before continuing. If you don't return the Promise of `showNotification`, the notification won't be sent yet once [`onPush`](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/onpush) completes. That said, Chrome expects a notification to be shown when a `onPush` is triggered. When none is sent, it will push a default notification.

**Pull request merged**
