### PR TITLE
Update grpc to 1.16.1 to support node 11

### PR DESCRIPTION
**Pull request by sunnylqm**
Need to update grpc dependency to 1.16.1 to support node 11 according to https://github.com/grpc/grpc-node/issues/594#issuecomment-439526215

### CODE REVIEW

**Comment by sunnylqm** [comment]
Just signed cla

**Comment by mikelehen** [comment]
Thanks!  Could you also update it in packages/functions and then re-run `yarn` from the root to update our `yarn.lock` file?

**Comment by LiteSoul** [comment]
Patiently waiting for Node 11 support 🙏

**Comment by mikelehen** [comment]
LGTM. @Feiyang1 feel free to merge.

**Pull request merged**
