### PR TITLE
Expose enable/DisableNetwork() via INTERNAL so it can be used in tests (but don't add to our .d.ts at least for now).

### PR DESCRIPTION
**Pull request by mikelehen**
@jshcrowthe I thought this would fix the issue with the integration tests, but there are still some failing for a different reason.  I'm not sure what's going on, and unfortunately I have to run.  I can't take a look until later tonight.  If this is blocking you, feel free to disable the minified integration tests for the moment. I'll figure it out tonight or tomorrow. :-/

### CODE REVIEW

**Comment by mikelehen** [comment]
Thanks for reviewing / merging!

I think I forgot to run "yarn prepare" from the root before running "yarn test" from integration/firestore which caused my confusion.  Perhaps we should make that automatic...

**Comment by jshcrowthe** [comment]
Yeah, I want to avoid unnecessary rebuilds as we can, but let's investigate more.

**Comment by wilhuff** [comment]
So ... when is `yarn prepare` required?

**Comment by jshcrowthe** [comment]
The npm `prepare` script is automatically run when you run `npm install`. We have a top level prepare script that runs all of the prepare scripts for the child packages on an install.

If you are needing to do cross package development (e.g. this case where we were depening on a module update), then the prepare script for the package you depend on needs to be run before you build. For this reason I wrote the custom `dev` script that coordinates the dev environments across all the SDKs so you can do this easily.

**Comment by mikelehen** [comment]
For us, I think `yarn prepare` is always required before running the integration/firestore tests that test the minified build (since that comes from packages/firestore).

**Pull request merged**
