### PR TITLE
6801 catch insecure indexedDB access

### PR DESCRIPTION
**Pull request by abilicz**
Related issue:
https://github.com/firebase/firebase-js-sdk/issues/6801

### CODE REVIEW

**Comment by hsubox76** [comment]
I'm trying to reproduce the error you showed here https://github.com/firebase/firebase-js-sdk/issues/6801#issuecomment-1332711754

I set Firefox to block all third-party cookies and I can't seem to reproduce it. When I type in "indexedDB" it says `IDBFactory {  }`. I'm using Firefox 107.0.1 on Mac. I went to Settings > Privacy & Security, set Browser Privacy to Custom, and set Cookies to "All third-party cookies (may cause websites to break)".

**Comment by abilicz** [comment]
I think the key part here is:

> Third party window content (e.g. [<iframe>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) content) cannot access IndexedDB if the browser is set to [never accept third party cookies](https://support.mozilla.org/en-US/kb/third-party-cookies-firefox-tracking-protection?redirectslug=disable-third-party-cookies&redirectlocale=en-US)

So if you will open for example this page https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe , open console and type `indexedDB` it will be fine, but if you change evaluation context to some iframe inside it will throw that error 
Screen Shot 2022-12-01 at 8 19 36 PM

For us this is an issue because we use Firebase from inside an iframe hosted by us, but iframe is inside Jira/Azure context , so top domain is different. Looks like some companies like to have this cookie policy set on some browsers. Unfortunately  Firefox throws some exception.

**Review by hsubox76 — APPROVED** [review]

**Comment by hsubox76** [comment]
Thanks! Got it. In that case the change looks good. Will merge when required checks pass.

**Comment by hsubox76** [comment]
Oops, looks like it failed the formatting check. Can you run `yarn format` on it?

**Pull request merged**
