### PR TITLE
Updated typings for database methods

### LINKED ISSUE #6071: rtdb: Reference#transaction return type
### [REQUIRED] Describe your environment

  * Operating System version: macOS
  * Browser version: N/A
  * Firebase SDK version: firebase-admin@10
  * Firebase Product: database

### [REQUIRED] Describe the problem

The `transaction` method on a reference is typed to return `Promise<any>` as opposed to `Promise<{ committed: boolean, snapshot: DataSnapshot }>`.

https://github.com/firebase/firebase-js-sdk/blob/a7f4a2eb6ed08596dffe75825bca1a2034bfcd2e/packages/database-types/index.d.ts#L140-L144

This is the same problem in the [docs](https://firebase.google.com/docs/reference/js/v8/firebase.database.Reference#transaction).

I'm happy to create a PR to update the above file, but not sure if that's the correct place to do this?

#### Steps to reproduce:

```js
const { getDatabase } = require('firebase-admin/database')

const result = await getDatabase().ref('blah').transaction(data => data)
```

Result is `any`

#### Relevant Code:

See above.

### PR DESCRIPTION
**Pull request by rhodgkins**
Fixes #6071. I've also update the return type for the `onComplete` handler that the methods also accept.

I've copied the comments for the `TransactionResult` interface from the corresponding `@firebase/database` package:

https://github.com/firebase/firebase-js-sdk/blob/14ccbadd034e1a702f7d91e70ec14856d445764f/packages/database/src/api/Transaction.ts#L42-L49

### CODE REVIEW

**Review by hsubox76 — COMMENTED** [review]
Looks good, in addition to the small nit about `readonly` (see comments), can you also add a changeset? To do this, run `yarn changeset` in the root of the repo and follow the prompts (select `database-types` as it suggests, then skip the "major" and "minor" options to let it default to "patch", then write a brief change note like "Updated typings for Reference methods"

**Comment by rhodgkins** [comment]
@hsubox76 thanks for the review, `readonly`s removed and change set added 👍

**Comment by hsubox76** [comment]
It seems like the `readonly` has been removed from `firebase/compat/index.d.ts` but not from `database-types/index.d.ts`, is that the case or is it a Github refresh issue on my end?

**Comment by rhodgkins** [comment]
> It seems like the `readonly` has been removed from `firebase/compat/index.d.ts` but not from `database-types/index.d.ts`, is that the case or is it a Github refresh issue on my end?

@hsubox76 ah sorry, totally missed that 🙈 


> `database-compat/src/api/Reference.ts` should be changed so the methods in conflict (update, remove, getPriority, etc) return `Promise<void>`

I'll have a go at changing those and see if that works :)

**Comment by rhodgkins** [comment]
@hsubox76 I've updated that file but there's still CI failures but its in a file I've not touched (I think anyway) - [`ERROR in /home/runner/work/firebase-js-sdk/firebase-js-sdk/packages/database/src/api/Database.ts`](https://github.com/firebase/firebase-js-sdk/runs/5698213257?check_suite_focus=true#step:8:407), is something else needed?

**Comment by hsubox76** [comment]
> @hsubox76 I've updated that file but there's still CI failures but its in a file I've not touched (I think anyway) - [`ERROR in /home/runner/work/firebase-js-sdk/firebase-js-sdk/packages/database/src/api/Database.ts`](https://github.com/firebase/firebase-js-sdk/runs/5698213257?check_suite_focus=true#step:8:407), is something else needed?

It was a flaky test. I re-ran it and it passed. Everything looks good, will merge!

**Comment by rhodgkins** [comment]
Ah great, thanks 👍

**Pull request merged**
