### PR TITLE
Removing RxFire

### PR DESCRIPTION
**Pull request by jamesdaniels**
We've decided to move RxFire to it's own repo, [firebaseextended/rxfire](https://github.com/firebaseextended/rxfire).

### CODE REVIEW

**Review by hsubox76 — APPROVED** [review]
Looks pretty thorough, thanks!

**Comment by Feiyang1** [comment]
@jamesdaniels Is it ready to be merged?

**Comment by jamesdaniels** [comment]
@Feiyang1 not yet, I need to get approval for the launch. Will ping you when we're green.

**Comment by jamesdaniels** [comment]
@Feiyang1 new repo is up and running. We're good to merge this.

**Comment by Feiyang1** [comment]
@jamesdaniels Awesome! would you mind fixing the conflict?

**Comment by jamesdaniels** [comment]
Will do. I think it's just the package.json changed whereas I deleted it.

**Pull request merged**
