### PR TITLE
point ENVIRONMENTS.md to devsite

### PR DESCRIPTION
**Pull request by Feiyang1**

### CODE REVIEW

**Comment by mmermerkaya** [comment]
Can we put this in README instead, and delete this file?

**Comment by hsubox76** [comment]
Seems like a good idea to put in README.md unless there are links to this page from somewhere or there is a convention for people to check for a file with this name.

**Comment by mmermerkaya** [comment]
Not sure about links to the file, but I'm pretty sure that there's no such convention. And I know that at least one user didn't notice the file :slightly_smiling_face: https://github.com/firebase/firebase-js-sdk/issues/880#issuecomment-401910371

**Comment by Feiyang1** [comment]
Moved the section to README

**Comment by mmermerkaya** [comment]
BTW, I think this PR fixes https://github.com/firebase/firebase-js-sdk/issues/914.

**Comment by Feiyang1** [comment]
Yay! One more closed issue.

**Pull request merged**
