### PR TITLE
Typo on changelog-generator

### PR DESCRIPTION
**Pull request by tbor00**
In this pr, fixed a typo in a variable name. It is a really very small change that does not affect any functionality or process.

### CODE REVIEW

**Comment by dwyfrequency** [comment]
> @dwyfrequency 👀

updating in https://github.com/firebase/firebase-js-sdk/pull/6760

**Comment by tbor00** [comment]
> > @dwyfrequency 👀
> 
> updating in #6760

yes, I saw it but I would like to know why this contribution is not merge and another PR was made for it, I was reading in the contributors documentation and I found nothing about it. 

it's just a doubt, don't take it the wrong way :)

**Review by dwyfrequency — APPROVED** [review]
LGTM

**Comment by dwyfrequency** [comment]
> > > @dwyfrequency 👀
> > 
> > 
> > updating in #6760
> 
> yes, I saw it but I would like to know why this contribution is not merge and another PR was made for it, I was reading in the contributors documentation and I found nothing about it.
> 
> it's just a doubt, don't take it the wrong way :)

Feel free to merge once the required tests are done running

**Pull request merged**
