### PR TITLE
Fix workflows for forks

### PR DESCRIPTION
**Pull request by jsoref**
### Discussion

#8274 

### Testing

✅  https://github.com/check-spelling-sandbox/firebase-js-sdk/actions/runs/9303577539

### CODE REVIEW

**Comment by jsoref** [comment]
Fwiw, I have a larger set of changes that would fix more of these -- but this small set is the first part that I trip on when using the repository...

**Comment by dlarocque** [comment]
Hi @jsoref, this is great, thanks for the PR!

There are changes in here that we would certainly want to have (e.g. upgrading versions), but others would need some closer review by the team. To help us break down the review process, could you create seperate PRs for all of the distinct changes in this PR so that we can review them individually?

**Comment by jsoref** [comment]
Sure

**Comment by jsoref** [comment]
That's the full split. My week is over. See you next week.

**Pull request closed without merging**
