### PR TITLE
use the firebase-exp version for `SDK_VERSION` in app-exp

### PR DESCRIPTION
**Pull request by Feiyang1**

### CODE REVIEW

**Comment by Feiyang1** [comment]
@avolkovi  FYI
@schmidt-sebastian Does Firestore use this value to track usage?

**Comment by schmidt-sebastian** [comment]
> @schmidt-sebastian Does Firestore use this value to track usage?

I don't think so. We use our own header: https://osscs.corp.google.com/firebase-sdk/firebase-js-sdk/+/master:packages/firestore/src/remote/rest_connection.ts;l=41

**Comment by Feiyang1** [comment]
@schmidt-sebastian Do you want to track the exp SDK usage? If so, I think we need to find a way to inject the version number to Firestore.

**Review by hsubox76 — APPROVED** [review]

**Comment by schmidt-sebastian** [comment]
> @schmidt-sebastian Do you want to track the exp SDK usage? If so, I think we need to find a way to inject the version number to Firestore.

Yes.

**Pull request merged**
