### PR TITLE
fix firestore node tests

### PR DESCRIPTION
**Pull request by Feiyang1**
Use babel to compile tests for Node testing, so that `import.meta.url` can be compiled correctly.

### CODE REVIEW

**Comment by Feiyang1** [comment]
fyi, @hsubox76

**Review by schmidt-sebastian — COMMENTED** [review]
I tried to use this via the IntelliJ test runner but it failed with the following error:

```

✖ ERROR: /Users/mrschmidt/GitHub/firebase/firebase-js-sdk/packages/firestore/test/register.ts:18
import firebase from '@firebase/app-compat';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

The diff for the change:

https://paste.googleplex.com/6380219926577152

We really need to find a way to make Firestore run via ts-node, as this allows us to debug in the IDE.

**Comment by Feiyang1** [comment]
I can debug tests fine with the new setup in IDE.  Are you not able to run tests at all?

**Comment by schmidt-sebastian** [comment]
No, I am not able to. I will play around with this some more (but not sure if I can get to it today)

**Review by schmidt-sebastian — APPROVED** [review]

**Review by hsubox76 — APPROVED** [review]

**Pull request merged**
