### PR TITLE
Run Storage Node tests in CI

### PR DESCRIPTION
**Pull request by dlarocque**
The script that runs the tests in CI accepts a `-s` flag we can use to pass **one** test command we want to run in CI. We were passing **two** commands, and only the first one (`test:browser`) was being run, skipping the Node tests. Now we only pass one command `test`, which runs both.

Since the Node tests in storage are currently failing, this means CI is now red until we fix it.

**Question**: Do we need to merge the fix for storage into this branch, so that we avoid CI being red in master?

### CODE REVIEW

**Comment by hsubox76** [comment]
> **Question**: Do we need to merge the fix for storage into this branch, so that we avoid CI being red in master?

Yes, we can't merge this into master as is.

**Review by hsubox76 — APPROVED** [review]
My only comment would be that I guess we deliberately removed the lint job from ci tests in order to run them in a separate workflow so I think technically we make another script here that doesn't run lint (seems to be called "test:all" in other packages), but I don't think it's that important.

**Comment by dlarocque** [comment]
> My only comment would be that I guess we deliberately removed the lint job from ci tests in order to run them in a separate workflow so I think technically we make another script here that doesn't run lint (seems to be called "test:all" in other packages), but I don't think it's that important.

I agree that we shouldn't run lint when testing, but I noticed that a lot of packages do this. Is this something we want to change in all packages?

**Comment by hsubox76** [comment]
> > My only comment would be that I guess we deliberately removed the lint job from ci tests in order to run them in a separate workflow so I think technically we make another script here that doesn't run lint (seems to be called "test:all" in other packages), but I don't think it's that important.
> 
> I agree that we shouldn't run lint when testing, but I noticed that a lot of packages do this. Is this something we want to change in all packages?

If it's in other packages, we can do another PR that gets them all later. This PR should be good to go.

**Pull request merged**
