### PR TITLE
fix: browser detection

### LINKED ISSUE #8299: [FirebaseServerApp] Failed to initialize in Next.JS Edge Runtime
### Operating System

N/A

### Browser Version

N/A

### Firebase SDK Version

10.12.2

### Firebase SDK Product:

Auth

### Describe your project's tooling

Next.JS

### Describe the problem

I cannot use `initializeServerApp` in **Next.JS middleware (Edge runtime)** to secure the server at middleware as intended.

However, just **commenting out `isBrowser()`** guard clause makes it **run as intended**.

I understand why it fails (Edge runtime is essentially the same as Browser runtime) and why the guard clause is there, but implementing security in Next.JS middleware is a life-saver in code complexity.

Third-party libraries like `next-firebase-auth-edge` require the use of service account credentials which is not ideal especially since `FirebaseServerApp` does what is required without the same.

### Steps and code to reproduce issue

1. Initialize Next.JS project.
2. Set up Firebase Auth on the client side.
3. Set up service worker to inject the `Authorization` header as in https://firebase.google.com/codelabs/firebase-nextjs
4. Set up Next.JS middleware to secure requests using `initializeServerApp` and `Auth`

```ts
// middleware.ts
const getIdTokenInServer = () => {
  const prefix = "Bearer ";
  const authorizationHeader = headers().get("Authorization");
  if (!authorizationHeader?.startsWith(prefix)) return null;
  return authorizationHeader.split(prefix)[1] ?? null;
};
const getFirebaseServerApp = () => {
  const idToken = getIdTokenInServer();
  // fails with guard clause but works fine if it's removed
  return initializeServerApp(
    firebaseConfig,
    idToken ? { authIdToken: idToken } : {},
  );
};
const getAuthInServer = () => getAuth(getFirebaseServerApp());
export async function middleware(req: NextRequest) {
  const auth = getAuthInServer();
  await auth.authStateReady()

  if (!auth.currentUser) return NextResponse.redirect(/** redirect url */);

  /** other authorization logic */

  return NextResponse.next();
}
```

### PR DESCRIPTION
**Pull request by JoseVSeb**
Update browser detection logic:
Detect either window or web worker (WorkerGlobalScope).

Fixes #8299 #8284

### CODE REVIEW

**Comment by jdgamble555** [comment]
Thanks for working on this guys!

**Comment by DellaBitta** [comment]
Hi @JoseVSeb,

Unfortunately adding `"WebWorker"` to the list of libs breaks our build enviornment. That lib includes symbols with the same name as those within other libs but with significantly different signatures.

I'm still working on this issue, though, and trying to find alternatives to a change that requires the use of `WorkerGlobalScope`. Could you please see if this code properly returns when you're in a webworker?

```
export function isWebWorker(): boolean {
  return !isNode() && typeof window === 'undefined' && typeof self !== 'undefined';
}
```

`isNode()` is the function in the same `enviornment.ts` file you added edits to. Thanks!

**Comment by JoseVSeb** [comment]
Hi @DellaBitta,

> ```
> export function isWebWorker(): boolean {
>   return !isNode() && typeof window === 'undefined' && typeof self !== 'undefined';
> }
> ```

this detects web worker fine but it also detects Edge runtime (unless `forceEnvironment` is set to `"node"`, not ideal), which was the issue to begin with.

> Unfortunately adding `"WebWorker"` to the list of libs breaks our build enviornment. That lib includes symbols with the same name as those within other libs but with significantly different signatures.

I added WebWorker to libs since I was using `WorkerGlobalScope` to detect web worker, but it's not technically necessary. If it's causing issues, just putting `declare class WorkerGlobalScope {}` in `environment.ts` might be enough.

I'll update the PR.

**Comment by JoseVSeb** [comment]
> The current PR adds a call to `isWebWorker()` to the implementation of `isBrowser()`, but there could be situations where this isn't quite valid. If some code wants to determine if they're in a browser, and expects all of the browser elements to be there, then this code could cause probelms because a Browser is also a WebWorker with this logic

I called `isWebWorker()` inside `isBrowser()` so as not to break the intention behind the previous commit (see #1773) affecting this function as I am not entirely sure of the impact of that commit. in https://github.com/firebase/firebase-js-sdk/pull/1773#discussion_r282602896, it refers this usage: https://github.com/firebase/firebase-js-sdk/blob/f6afa45fe24f7adf5ea9a672100049c2ca8571db/packages/app/index.ts#L26

-----

> ```
>   if (isBrowser() && !isWebWorker()) {
> ```

did you mean `isBrowser() || isWebWorker()`? Since `window` and `WorkerGlobalScope` are never both defined in the same place, checking `isBrowser() && !isWebWorker()` is the same as just checking `isBrowser()`. also, `FirebaseServerApp` can technically work in a web worker and there are scenarios where that might be needed. so, in my opinion, if we are to remove `isWebWorker()` check from inside `isBrowser()`, `initializeServerApp` should check for just `window`.

-----

> This would mean that the PR doesn't fix issue https://github.com/firebase/firebase-js-sdk/issues/8284 (the Auth Lite issue), but perhaps it will enable FirebaseServerApp in those environments. I can escalate that issue with the Auth team directly.

I'm not exactly certain of that issue but https://github.com/firebase/firebase-js-sdk/issues/8284#issuecomment-2143211069 seems to suggest that this could be a possible fix, that's why I mentioned it.

**Comment by DellaBitta** [comment]
I suppose it's worth mentioning some of the team's goals: 

 - I'm trying to get to place where `initializeServerApp()` is enabled for WebWorkers, at least experimentally.
- Currently `initializeServerApp()` throws an error for WebWorkers because `isBrowser()` is returning `true` when running in a WebWorker. We want to fix this.
 - As a team we don't want `FirebaseServerApp` to be used in standard browser environments (ie: non-WebWorkers) so we want `initializeServerApp()` to still throw an error for standard browser runtimes.
 - If we keep the implementation of `isBrowser()` as it is right now, it can be used as a tool to detect an environment that is in a browser and is NOT a web worker, ie: `(isBrowser() && !isWebWorker())`, which is advantageous for the SDK.
 - `isBrowser()` is used by the Auth Compat SDK, too. I would rather not change the Auth Compat SDK's behavior (by changing the `isBrowser()` implementation) as that could have unknown repercussions. We can further consult the Auth team but that will take some time.
 - With all of this, I think the best path forward is to add the `isWebWorker()` function, keep `isBrowser()` as is, and update `initializeServerApp()` so that it allows WebWorkers to proceed without throwing an error:

```
if (isBrowser() && !isWebWorker()) {
    // FirebaseServerApp isn't designed to be run in browsers.
    throw ERROR_FACTORY.create(AppError.INVALID_SERVER_APP_ENVIRONMENT);
}
```

I know this is a lot, so if you'd rather I do this this work in a new PR then let me know!

**Comment by DellaBitta** [comment]
Please revert the change to isBrowser's implementation and then we should be good to go!

**Comment by JoseVSeb** [comment]
@DellaBitta, I raised this PR *because*  `isBrowser()` has issues. The existing logic uses `self` to detect a browser, which returns `true` for every runtime that has `self` defined (not just browser), including **Next.JS Edge Runtime**, which is one of the two reasons behind #8299. Edge Runtime is NOT a web worker.

I traced the source of change to #1773 where browser detection was changed from `window` to `self` and the reasoning stated as *"Web Workers are browser too"*.

I raised this PR so that `isBrowser` does what it's supposed to do and also, not break #1773; explicitly detecting either `window` or `WorkerGlobalScope` (for web worker) so that it covers both the runtimes available in a browser and not detect other runtimes, which solves the first cause of #8299 (second cause is covered by #8320).

**Comment by DellaBitta** [comment]
Ah, I see! Sorry for the confusion. This looks ok to me but let me get one more pair of eyes on it.

**Review by jamesdaniels — APPROVED** [review]

**Review by DellaBitta — APPROVED** [review]

**Comment by DellaBitta** [comment]
Merging. Thanks for the contribution!

**Pull request merged**
