### PR TITLE
Upgrade GRPC to 1.13.1

### PR DESCRIPTION
**Pull request by schmidt-sebastian**
Addresses https://github.com/grpc/grpc-node/issues/453 in Firestore.

Also fixes https://github.com/firebase/firebase-js-sdk/issues/1036

### CODE REVIEW

**Comment by Slapbox** [comment]
Is there an eta for a new release to npm?

**Comment by hiranya911** [comment]
@Slapbox Possibly later this week.

**Comment by Slapbox** [comment]
Thanks very much for the update @hiranya911

**Comment by schmidt-sebastian** [comment]
We are having some trouble with our release pipeline and are actively working on pushing the new release. Thanks for your patience.

**Comment by Slapbox** [comment]
@schmidt-sebastian Thanks very much for the update. The community definitely appreciates it!

**Comment by k0d3d** [comment]
using gprc@1.13.1 also fixes it. I had to remove node_modules and edit package-lock.json before `npm i gprc@1.13.1 --force` to make sure it worked

**Pull request merged**
