### PR TITLE
Ensure app-types package includes private.d.ts

### PR DESCRIPTION
**Pull request by jshcrowthe**
Fixes an issue introduced with the type refactor (i.e. #334)

### CODE REVIEW

**Comment by vyasm9** [comment]
Hi guys, I am working on Ionic2 project with firebase

**I tried this**

Inside package.json, remove ^ from "firebase": "^4.8.1"
1.1 Downgrade Firebase from 4.8.1 to 4.8.0 by changing 4.8.1 to 4.8.0
1.2 End result should look like this: "firebase": "4.8.0"
Run npm update in the Project Root. NPM will downgrade Firebase for ya
Run ionic serve to check for compilation errors

**But unable to resolve the following issue in ionic2**

typescript: Users/vyas/node_modules/@firebase/database/dist/esm/src/api/Database.d.ts, line: 4
Cannot find module '@firebase/app-types/private'.

   L3:  import { FirebaseApp } from '@firebase/app-types';
   L4:  import { FirebaseService } from '@firebase/app-types/private';
[08:59:27] typescript: ...rs/vyas/node_modules/@firebase/database/dist/esm/src/core/AuthTokenProvider.d.ts, line: 17
Cannot find module '@firebase/app-types/private'.

  L16:  getToken(forceRefresh: boolean): Promise<FirebaseAuthTokenData>;
  L17:  addTokenChangeListener(listener: (token: string | null) => void): void;
  L18:  removeTokenChangeListener(listener: (token: string | null) => void): void;

**Can any body help me with this.**

**Comment by MaryCooperGD** [comment]
Hi, I still have the issue of `Cannot find module '@firebase/app-types/private'.` . I've tried following [this solution](https://stackoverflow.com/questions/47949311/cannot-find-module-firebase-app-types-private-firebase-throws-error/47949323#47949323) but it's still saying me this:


`npm WARN angularfire2@5.0.0-rc.4 requires a peer of @angular/common@^5.0.0 but none is installed. You must install peer dependencies yourself.`
`npm WARN angularfire2@5.0.0-rc.4 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.`
`npm WARN angularfire2@5.0.0-rc.4 requires a peer of @angular/platform-browser@^5.0.0 but none is installed. You must install peer dependencies yourself.`
`npm WARN angularfire2@5.0.0-rc.4 requires a peer of @angular/platform-browser-dynamic@^5.0.0 but none is installed. You must install peer dependencies yourself.`
`npm WARN angularfire2@5.0.0-rc.4 requires a peer of firebase@^4.5.0 but none is installed. You must install peer dependencies yourself.`
`npm WARN angularfire2@5.0.0-rc.4 requires a peer of rxjs@^5.5.2 but none is installed. You must install peer dependencies yourself.`

**Comment by emmanuelagarry** [comment]
I still have the same problem too. I have tried every thing too

**Comment by emmanuelagarry** [comment]
I have the same problem, I have tried everything too

**Comment by jshcrowthe** [comment]
With the holidays, this has not yet been released. Look for this to be resolved in this weeks release!

**Comment by lakeside763** [comment]
Hi, I still have the issue
ERROR in ../node_modules/@firebase/database/dist/esm/src/api/Database.d.ts(4,33): error TS2307: Cannot find module '@firebase/app-types/private'.
../node_modules/@firebase/database/dist/esm/src/core/AuthTokenProvider.d.ts(17,39): error TS2307: Cannot find module '@firebase/app-types/private'.

I have downgraded my firebase and is still the same
"angularfire2": "^5.0.0-rc.4",
"firebase": "^4.8.0",

**Comment by chezdrz** [comment]
even I am facing the same problem suddenly. 
Earlier everything was working fine. 

I downgraded to "firebase": "^4.8.0",
and did an npm install 
it did not solve the problem.

**Comment by prantikv** [comment]
@chezdrz did you find any solution to this? I am facing the same issue.

**Comment by lakeside763** [comment]
perform the following steps
1. npm uninstall firebase
2. install firebase latest release (npm install firebase). firebase 4.9.0 will be installed.
3. in your application src code replace firebase typings as follows
4. replace:   import * as firebase from 'firebase'
5. to:  import * as firebase from 'firebase/app' throughout your src  code application

Hopefully it should work fine

**Comment by lakeside763** [comment]
perform the following steps

   1. npm uninstall firebase
   2. install firebase latest release (npm install firebase). firebase
   4.9.0 will be installed.
   3. in your application src code replace firebase typings as follows
   4. replace: import * as firebase from 'firebase'
   5. to: import * as firebase from 'firebase/app' throughout your src code
   application

Hopefully it should work fine

**Pull request merged**
