### PR TITLE
Switch from 'grpc' to '@grpc/grpc-js' dependency.

### LINKED ISSUE #1783: FR: Replace grpc with grpc-js
Hi, I noticed that last week the https://github.com/googleapis/nodejs-firestore package got rid of the grpc node native addon and replaced it with `@grpc/grpc-js`. I was wondering if this package was planning on upgrading to `grpc-js` to remove the complexity of dealing with compiled node addons for different platforms like node and electron. I couldn't find any discussion on this in the issue tracker. Thanks!

### PR DESCRIPTION
**Pull request by mikelehen**
Fixes #1783, reduces package size, and should ease compatibility issues with Electron, etc.

### CODE REVIEW

**Comment by jeffreypriebe** [comment]
@mikelehen This seems great, but the latest release of @firebase/firestore now doesn't work on node 6 with this, given [@grpc/grpc-js requirement for node v8](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/package.json#L9).

Is there a reasonable remedy?
Is this node v6 support a non-goal for firestore at this point (we're using this with firestore and have had trouble with Google cloud functions in node 8 [we moved to node 8 and had to roll back] [per this issue](https://github.com/firebase/firebase-functions/issues/429)).

**Comment by mikelehen** [comment]
@jeffreypriebe To be clear, are you using the [firebase](https://www.npmjs.com/package/firebase) npm module (in which case this is the right github repo)?  Or are you using [https://www.npmjs.com/package/firebase-admin](https://www.npmjs.com/package/firebase-admin) or [@google-cloud/firestore](https://www.npmjs.com/package/@google-cloud/firestore)?

**Comment by mikelehen** [comment]
@jeffreypriebe (I'm asking because usually you would use firebase-admin if you're using Cloud Functions...

**Comment by mikelehen** [comment]
@jeffreypriebe We've ended up reverting this change (will be in the next release) since it is a breaking change to remove support for v6.  We will hold off until our next breaking change release.

That said, node v6 has reached end-of-life (https://github.com/nodejs/Release#end-of-life-releases) and you should definitely strive to upgrade when you can.

**Pull request merged**
