### PR TITLE
Firestore API Changes

### PR DESCRIPTION
**Pull request by schmidt-sebastian**
Pulling in the firestore-api-changes branch.

```
- [changed] Snapshot listeners (with the `includeMetadataChanges` option
   enabled) now receive an event with `snapshot.metadata.fromCache` set to
  `true` if the SDK loses its connection to the backend. A new event with
  `snapshot.metadata.fromCache` set to false will be raised once the
   connection is restored and the query is in sync with the backend again.
- [added] Added `SnapshotOptions` API to control how DocumentSnapshots 
  return unresolved server timestamps.
- [changed] For non-existing documents, `DocumentSnapshot.data()` now returns 
  `undefined` instead of throwing an exception. A new 
  `QueryDocumentSnapshot` class is introduced for Queries to reduce the number 
  of undefined-checks in your code.
- [added] Added `isEqual` API to `GeoPoint`, `Blob`, `SnapshotMetadata`, 
  `DocumentSnapshot`, `QuerySnapshot`, `CollectionReference`, `FieldValue`
  and `FieldPath`.
```

Note that I have manually added missing entries to the Changelog.

### CODE REVIEW

**Comment by schmidt-sebastian** [comment]
Test are failing with quota exceeded:

```
@firebase/firestore: Firestore (4.8.2) 2018-01-12T04:07:50.205Z: FirebaseError: [code=resource-exhausted]: Quota exceeded.
@firebase/firestore: Firestore (4.8.2) 2018-01-12T04:07:50.205Z: Using maximum backoff delay to prevent overloading the backend.
@firebase/firestore: Firestore (4.8.2) 2018-01-12T04:07:55.208Z: FirebaseError: [code=resource-exhausted]: Quota exceeded.
@firebase/firestore: Firestore (4.8.2) 2018-01-12T04:07:55.208Z: Using maximum backoff delay to prevent overloading the backend.
```

**Comment by merlinnot** [comment]
@schmidt-sebastian You might want to take a look at https://groups.google.com/d/msg/firebase-talk/BJIsr9ehH1o/5Chjw81jBAAJ

**Comment by schmidt-sebastian** [comment]
@jshcrowthe Can you approve the changes in yarn.lock?

I re-ran the tests just after midnight and they passed. Can we enable billing on our test project?

**Comment by jshcrowthe** [comment]
Billing has been enabled so we shouldn't see quota issues anymore

**Pull request merged**
