### PR TITLE
Clean up and re-enable some OR query tests.

### PR DESCRIPTION
**Pull request by ehsannas**

### CODE REVIEW

**Comment by milaGGL** [comment]
There are duplicate test cases in 2 "OR queries". Please remove it. for example: https://github.com/firebase/firebase-js-sdk/blob/e30d7a6522fd3be0c30a82ee054b271a68c03fde/packages/firestore/test/integration/api/query.test.ts#L2384 and https://github.com/firebase/firebase-js-sdk/blob/e30d7a6522fd3be0c30a82ee054b271a68c03fde/packages/firestore/test/integration/api/query.test.ts#L2116

**Comment by milaGGL** [comment]
In the second "OR queries", only 3 tests require composite index, 'can use query overloads','can use or queries','supports multiple in ops'. 
I suggest merge all other test cases into one "OR queries", except for the above 3.

**Comment by ehsannas** [comment]
> In the second "OR queries", only 3 tests require composite index, 'can use query overloads','can use or queries','supports multiple in ops'.
I suggest merge all other test cases into one "OR queries", except for the above 3.

Yep, I have 
- Removed the duplicate tests that did not need a composite index.
- Kept `can use query overloads` and `can use or queries`
- Slightly modified `supports multiple in ops` so it doesn't need a composite index (by using an equality instead of inequality in the filter). This modification doesn't change what we're testing, and makes it possible to run without a composite index.

**Review by milaGGL — APPROVED** [review]
LGTM

**Pull request merged**
