### PR TITLE
Use RTDB emulator v4.9.0

### PR DESCRIPTION
**Pull request by fredzqm**
Was just releasing it in CLI: https://github.com/firebase/firebase-tools/pull/5000/

### CODE REVIEW

**Comment by fredzqm** [comment]
Will wait after code freeze~

**Comment by fredzqm** [comment]
Got the CLI PR merged. Mind a stamp here?

**Comment by maneesht** [comment]
LGTM

**Comment by fredzqm** [comment]
@hsubox76 This PR has been sitting here for a while. It's pretty trivial, just updating the RTDB emulator version used in tests. Can we get this in?

**Comment by fredzqm** [comment]
@hsubox76 Mind taking a look and submit this?

Thanks! We have another emulator release now.

**Review by hsubox76 — APPROVED** [review]

**Pull request merged**
