### PR TITLE
Fix FetchProvider in non-browser environment

### LINKED ISSUE #7633: @firebase/auth: Auth (10.3.0): INTERNAL ASSERTION FAILED: Could not find fetch implementation, make sure you call FetchProvider.initialize() with an appropriate polyfillTitle for the bug
### Operating System

N/A

### Browser Version

N/A

### Firebase SDK Version

firebase@10.3.0, @firebase/auth@1.3.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Next.js with Vercel Edge runtime.

### Describe the problem

When running Firebase, I get the following error:

```
@firebase/auth: Auth (10.3.0): INTERNAL ASSERTION FAILED: Could not find fetch implementation, make sure you call FetchProvider.initialize() with an appropriate polyfill
```

### Steps and code to reproduce issue

*I checked the code and I believe it's quite simple to verify this is a bug, and I will describe it below. Thus I don't provide a detailed repilication. Let me know if you still want me to prepare a minimal repo to reproduce this bug.*

- The package [`@firebase/auth@1.3.0`](https://unpkg.com/browse/@firebase/auth@1.3.0/package.json) provides multiple exports, shown in its package.json. One of them is `dist/esm2017/index.js`. 
- [`dist/esm2017/index.js`](https://unpkg.com/browse/@firebase/auth@1.3.0/dist/esm2017/index.js) just re-exports some objects from `dist/esm2017/index-9a76d29a.js`.
- [`dist/esm2017/index-9a76d29a.js`](https://unpkg.com/browse/@firebase/auth@1.3.0/dist/esm2017/index-9a76d29a.js) defines `class FetchProvider` at line 742, and calls `FetchProvider.fetch()` at line 915 and line 1470. However, `FetchProvider.initialize()` has never been called in this file, and [`self`](https://developer.mozilla.org/en-US/docs/Web/API/Window/self) is not a standard JavaScript global property (it only exists in browser environment). That's why I get this error.

### PR DESCRIPTION
**Pull request by ocavue**
### Discussion
 
This PR tries get the fetch implementation from not only `self` but also standard [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis). This would allow Firebase to get the fetch implementation in non-browser JavaScript environment, like [Vercel Edge Runtime](https://vercel.com/docs/functions/edge-functions/edge-runtime).

Closes https://github.com/firebase/firebase-js-sdk/issues/7633
Closes https://github.com/firebase/firebase-js-sdk/issues/7533

### Testing

N/A

### API Changes

No API changes

### CODE REVIEW

**Comment by prameshj** [comment]
Looks good to me.. @hsubox76 FYI

**Comment by hsubox76** [comment]
Can you add a changeset? Run `yarn changeset`. Should be a `patch` for `@firebase/auth`. This ensures that this change will be released. The text in the description should be fine for the text in the changeset note.

**Comment by ocavue** [comment]
@hsubox76 Changeset file has been added

**Review by prameshj — APPROVED** [review]

**Comment by prameshj** [comment]
Requesting review from @hsubox76 or @DellaBitta , thanks!

**Review by hsubox76 — APPROVED** [review]
I don't want to hold this PR up but in the future we should think about putting any changes we need to make global variable checking more robust in this function in `firebase/util` and using it in all places that need `globalThis`: https://github.com/firebase/firebase-js-sdk/blob/master/packages/util/src/global.ts#L23 I think it's only used in two places right now but we should check if there's any other instances of `self` that would benefit from it.

**Comment by hsubox76** [comment]
Sorry, this is my fault for the delay, but it looks like triggering a re-run of the failed jobs doesn't work because the build artifact it's trying to use has expired. Can you push an empty commit to trigger a new CI run?

**Comment by ocavue** [comment]
I pushed a new empty commit. The workflow requires approval to run.

**Review by ryohei1216 — APPROVED** [review]

**Comment by ryohei1216** [comment]
Sorry, I made the same mistake too 🙏 
Can you push an empty commit to trigger a new CI run?

**Pull request merged**
