### PR TITLE
Use the latest published version for auth sample app

### PR DESCRIPTION
**Pull request by renkelvin**
Upgrade the sample app build file so that the latest published Firebase libs are for auth sample app.

### CODE REVIEW

**Review by Xiaoshouzi-gh — APPROVED** [review]
LGTM

**Review by NhienLam — APPROVED** [review]

**Comment by DellaBitta** [comment]
Could you please add a PR description?

**Comment by renkelvin** [comment]
> Could you please add a PR description?

Added, it's similar to the title though.

**Comment by renkelvin** [comment]
> Could you please add a PR description?

@DellaBitta Btw, do you know if the Firestore CI failures can be ignored?

**Comment by DellaBitta** [comment]
> > Could you please add a PR description?
> 
> @DellaBitta Btw, do you know if the Firestore CI failures can be ignored?

we can re-run them.

**Pull request merged**
