### PR TITLE
Finish off the emulator hooks

### PR DESCRIPTION
**Pull request by samhorlbeck**

### CODE REVIEW

**Review by yuchenshi — APPROVED** [review]
Emulator paths (APIs + widget) looks good to me

**Comment by yuchenshi** [comment]
Is there anything we need to do with compact?

**Comment by samhorlbeck** [comment]
No; now that it's on the auth object itself the compat object should inherit it

**Review by yuchenshi — APPROVED** [review]
One last thing -- please also set `appVerificationDisabledForTesting` to `true` on `.useEmulator` call per design doc. Otherwise, this is good to go.

**Comment by yuchenshi** [comment]
Is this PR good to go?

**Pull request merged**
