### PR TITLE
Fix modular autoinit breakage

### LINKED ISSUE #6662: Uncaught TypeError: can't access property "__FIREBASE_DEFAULTS__", process.env is undefined
### Describe your environment

  * Operating System version:  Arch Linux, Kernel 5.19.13
  * Browser version: Firefox Developer Edition 106.0b8
  * Firebase SDK version: 9.11.0
  * Firebase Product: the issue is in `util`

#### Steps to reproduce:
1. Use the Firebase JS client SDK in an environment where `process` is defined, but `process.env` isn't, like Nuxt 3 in the browser.
2. Observe the following error in the console:

```
Uncaught TypeError: can't access property "__FIREBASE_DEFAULTS__", process.env is undefined
```

### PR DESCRIPTION
**Pull request by bcspragu**
I ran into this issue updating dependencies for a Nuxt 3 app. The problem is that `process.{client,server,dev}` are defined even on the client, so the client ends up broken with errors like:

```
Uncaught TypeError: can't access property "__FIREBASE_DEFAULTS__", process.env is undefined
```

Since the code only uses `process.env`, this updates the check to look explicitly for `process.env`.

Fixes #6662

### CODE REVIEW

**Comment by hsubox76** [comment]
Thank you! Can you add a changeset for `@firebase/util`? Patch should be fine.

**Comment by bcspragu** [comment]
Should be all set, updated `@firebase/util` to `1.7.1`

**Comment by hsubox76** [comment]
Thanks! Just fyi, we use `changesets` so instead of altering the package.json directly, you'd need to follow the directions in the "No Changeset Found" comment above.

But it turns out I also have to make other fixes in that file due to https://github.com/firebase/firebase-js-sdk/issues/6660 so I can just put this fix in the same PR so we won't run into any merge conflicts or anything and you don't have to worry about the changeset tool.

**Comment by hsubox76** [comment]
Rolling this fix into https://github.com/firebase/firebase-js-sdk/pull/6665

**Comment by bcspragu** [comment]
Sounds good to me, and sorry for glossing over the (very clearly laid out) instructions!

**Pull request closed without merging**
