### PR TITLE
Add changeset for v9

### PR DESCRIPTION
**Pull request by Feiyang1**

### CODE REVIEW

**Review by hsubox76 — COMMENTED** [review]
2 questions:
1) Is firestore special? (no compat or types)?
2) Should we also bump interop types packages?

**Comment by Feiyang1** [comment]
> 2 questions:
> 
> 1. Is firestore special? (no compat or types)?

Waiting on https://github.com/firebase/firebase-js-sdk/pull/5319

> 2. Should we also bump interop types packages?

nop, they have no changes.

**Comment by hsubox76** [comment]
> > 1. Should we also bump interop types packages?
> 
> nop, they have no changes.

Ok just want to double check that the new messaging one we just made will get published. I get confused about how changeset works.

**Comment by Feiyang1** [comment]
I thought I included it (messaging-interop-types), but apparently I didn't. Good catch.

**Review by hsubox76 — APPROVED** [review]
Approved pending firestore updates.

**Pull request merged**
