### PR TITLE
Infer database URL from Project ID

### PR DESCRIPTION
**Pull request by schmidt-sebastian**

### CODE REVIEW

**Comment by schmidt-sebastian** [comment]
@jsdt - Do you mind taking a look?

**Comment by jsdt** [comment]
Will this work for old projects?

**Comment by schmidt-sebastian** [comment]
@jsdt Do you have specific concerns? It will use the databaseURL param from the configuration if provided.

**Comment by fredzqm** [comment]
Old projects will still have `databaseUrl` in the config.json.
New projects that conform to the new naming convention will no long have `databaseUrl` and this inferrerence will kick in.

**Review by jsdt — APPROVED** [review]

**Review by hsubox76 — APPROVED** [review]

**Pull request merged**
