### PR TITLE
handle undefined document, window variables in BrowserPlatform

### PR DESCRIPTION
**Pull request by Bunkerbewohner**
Simple fix for the problem described in https://github.com/firebase/firebase-js-sdk/issues/1138

### CODE REVIEW

**Comment by Bunkerbewohner** [comment]
I signed the CLA!

**Comment by schmidt-sebastian** [comment]
Thanks for sending this over. I would like to go one step further and verify that "window" and "document" are known types before accessing them. I have seen some platforms (such as Node) that error even when checks like "window || null" are performed.

See follow up PR #1140.

**Comment by Bunkerbewohner** [comment]
Ooops seems like I accidently pushed the wrong code and didn't even notice it. My bad. You are of course right that just ORing with null is not sufficient. Thanks for the follow up PR!

I updated my PR just for the sake of correctness.

**Comment by schmidt-sebastian** [comment]
Thanks for updating this. I have merged my follow-up PR, which uses the same logic you have added in this PR. I will close this PR as #1140 is merged. Thanks!

**Pull request closed without merging**
