### PR TITLE
Adding TOC fixes and some revised comments.

### PR DESCRIPTION
**Pull request by egilmorez**
Hey there! So you want to contribute to a Firebase SDK? 
Before you file this pull request, please read these guidelines:

### Discussion

  * Read the contribution guidelines (CONTRIBUTING.md).
  * If this has been discussed in an issue, make sure to link to the issue here. 
    If not, go file an issue about this **before creating a pull request** to discuss.

### Testing

  * Make sure all existing tests in the repository pass after your change.
  * If you fixed a bug or added a feature, add a new test to cover your code.

### API Changes

  * At this time we cannot accept changes that affect the public API.  If you'd like to help 
    us make Firebase APIs better, please propose your change in an issue so that we 
    can discuss it together.

### CODE REVIEW

**Comment by hsubox76** [comment]
Need to resolve conflicts, git pull first, resolve conflicts, recommit and push.  I think the conflict on index.d.ts is one line that we added back since you last checked the file out on 1125 (https://github.com/firebase/firebase-js-sdk/pull/1607/files).  For the toc you can just "use yours", your local copy should be the one we want.

**Comment by egilmorez** [comment]
Strangely git pull seemed to think I was "already up to date" and had "nothing to commit, working tree clean."

Changing my git config also seems to have added some extra reviewers :)

**Comment by egilmorez** [comment]
Reviewers please note: I am almost certainly going to abandon this request, clean up my config, and start again.  Sorry for the noise :)

**Comment by egilmorez** [comment]
I've fixed my CLA problem, but seem to have some other issues.  Lemme start again from a clean slate :)

**Pull request closed without merging**
