### PR TITLE
Add a stopgap idb replacement

### PR DESCRIPTION
**Pull request by hsubox76**
Replace `idb` dependency with a temporary set of methods in `@firebase/util`. This is to address an increasing amount of mostly Node ESM module related problems caused by depending on an old version of `idb`. Upgrading to idb 7+ may also fix many of these problems but would require dropping IE support.

In the interest of reducing the amount of surface area for error, I have only filled in the minimum idb methods and properties currently being used by our consuming libraries. We are planning on extracting a more fully featured idb promise wrapper library from Firestore in the near future.

Although these methods won't work in Node, I am exporting them from the `@firebase/util` Node entry point also, otherwise if an app compiles in Node mode (like an SSR app), it'll break on build when the packages try to import these methods. Errors can be avoided by using isSupported() to prevent initialization of relevant products.

### CODE REVIEW

**Review by jamesdaniels — APPROVED** [review]

**Comment by ewanmay** [comment]
Hey folks, loyal firebase user here. Just wondering if we have an ETA on merging? Not trying to rush you at all but a few of us can't develop right now. We are relying on many of the features in V9 that make it difficult to roll back.

**Comment by everbliss7** [comment]
> 

Same here, we have stopped working on our current project until the fix.

**Comment by edi** [comment]
Waiting :)

**Review by elsowiny — APPROVED** [review]

**Comment by quckslvr** [comment]
Hi everyone, while waiting for the merge I tried the 9.6.3 version and it works.
Soas a workaround you can install this version while waiting for the approval :D

**Comment by Santoshah** [comment]
Is there any relese for version 8 ?

**Review by zwu52 — APPROVED** [review]
LGTM

**Comment by hsubox76** [comment]
If we get approvals this should go out in Thursday's release (March 17).

**Review by allspain — APPROVED** [review]

**Comment by alexiscavaroc** [comment]
> > Hi everyone, while waiting for the merge I tried the 9.6.3 version and it works. So as a workaround you can install this version while waiting for the approval :D
> 
> No such luck for me

9.6.3 didn't work for me, but 9.6.1 did ;)

**Comment by JamesOwen7** [comment]
Hi there, new firebase user and I'm encountering the error "Can't find variable: IDBIndex" error. Is this what is being discussed on here...?

**Comment by ewanmay** [comment]
@JamesOwen7 Yes

**Comment by thegirlyoucallryan** [comment]
Has this been fixed?  I tried downgrading to older packages but nothing is working for me.

**Comment by ewanmay** [comment]
Can confirm this is fixed in production

Use version 9.6.9 (The latest as of this post) and you should be all good to go!

**Comment by edi** [comment]
Yes, all working fine. Now can someone please look into #5848 ?

It’s really affecting everyone who uses firebase storage in RN ..

**Comment by Santoshah** [comment]
Is this also released for firebase version 8 ?

**Comment by wortkotze** [comment]
Sry I receive still the following error:
[Unhandled promise rejection: FirebaseError: Remote Config: Indexed DB is not supported by current browser (remoteconfig/indexed-db-unavailable).] 
in Version 9.6.9
has the fix been applied there?

thx

**Comment by TheBigOx** [comment]
> Sry I receive still the following error: [Unhandled promise rejection: FirebaseError: Remote Config: Indexed DB is not supported by current browser (remoteconfig/indexed-db-unavailable).] in Version 9.6.9 has the fix been applied there?
> 
> thx

I also get the issue on version 9.6.9 and 9.6.10

**Pull request merged**
