### PR TITLE
Update the test:setup script to configure firestore settings

### PR DESCRIPTION
**Pull request by jshcrowthe**
It seems some styling things got missed by another PR (i.e. #232)

This just augments the `test:setup` script to properly configure firestore

### CODE REVIEW

**Comment by gauntface** [comment]
Also looks like the messaging integration tests are failling, has this been an ongoing issue? they passed for my previous PR (I think)

**Comment by jshcrowthe** [comment]
@gauntface I've seen your integration tests time out from time to time. It is really inconsistent. We can try bumping the timeouts?

**Comment by gauntface** [comment]
timeouts and retries should make it more stable. Happy to take a look in a seperate PR unless you want to try in this one.

**Comment by jshcrowthe** [comment]
Lets do it in a separate one.

**Pull request merged**
